### ISSUE TITLE
Panic when creating new branch on large repository

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#2640]
```
❯ git town hack test
panic: "TO DELETE ⚠️" is not a valid remote branch name

goroutine 1 [running]:
github.com/git-town/git-town/v10/src/domain.NewRemoteBranchName({0x14000113842, 0x10})
	github.com/git-town/git-town/v10/src/domain/remote_branch_name.go:17 +0x8c
github.com/git-town/git-town/v10/src/git.determineSyncStatus({0x140001137bc, 0x3b}, {0x14000113841, 0x3a})
	github.com/git-town/git-town/v10/src/git/backend_commands.go:194 +0xf8
github.com/git-town/git-town/v10/src/git.ParseVerboseBranchesOutput({0x1400010c000, 0x8db1})
	github.com/git-town/git-town/v10/src/git/backend_commands.go:161 +0x4e0
github.com/git-town/git-town/v10/src/git.(*BackendCommands).BranchesSnapshot(0x1400024d410)
	github.com/git-town/git-town/v10/src/git/backend_commands.go:96 +0x9c
github.com/git-town/git-town/v10/src/execute.LoadBranches({0x1400024d400, 0x1, 0x0, 0x1, 0x1400024b260, 0x1, 0x1, 0x0})
	github.com/git-town/git-town/v10/src/execute/load_branches.go:18 +0xa8
github.com/git-town/git-town/v10/src/cmd.determineHackConfig({0x14000192b70, 0x1, 0x3?}, 0x1400024d400, 0x0)
	github.com/git-town/git-town/v10/src/cmd/hack.go:82 +0x128
github.com/git-town/git-town/v10/src/cmd.executeHack({0x14000192b70, 0x1, 0x1}, 0x0)
	github.com/git-town/git-town/v10/src/cmd/hack.go:55 +0x90
github.com/git-town/git-town/v10/src/cmd.hackCmd.func1(0x1400025cc00?, {0x14000192b70, 0x1, 0x1})
	github.com/git-town/git-town/v10/src/cmd/hack.go:36 +0x44
github.com/spf13/cobra.(*Command).execute(0x14000249b00, {0x14000192b30, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x14000240000)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/git-town/git-town/v10/src/cmd.Execute()
	github.com/git-town/git-town/v10/src/cmd/core.go:33 +0x308
main.main()
	github.com/git-town/git-town/v10/main.go:22 +0x30
```

Not sure where `TO DELETE ⚠️` comes from. I also saw it displayed as:
```
panic: "Fix" is not a valid remote branch name
```
On another repository.

I don't have branches with those names.

**Comment by lud-wj** [comment]
Same error:

```
git repo
panic: "ci skip" is not a valid remote branch name

goroutine 1 [running]:
github.com/git-town/git-town/v10/src/domain.NewRemoteBranchName({0xc00028a637, 0x7})
        /home/kevlar/git-town/src/domain/remote_branch_name.go:17 +0x94
github.com/git-town/git-town/v10/src/git.determineSyncStatus({0xc00028a5b6, 0x1d}, {0xc00028a636, 0x18})
        /home/kevlar/git-town/src/git/backend_commands.go:194 +0x107
github.com/git-town/git-town/v10/src/git.ParseVerboseBranchesOutput({0xc000288000, 0x66b1})
        /home/kevlar/git-town/src/git/backend_commands.go:161 +0x591
github.com/git-town/git-town/v10/src/git.(*BackendCommands).BranchesSnapshot(0xc0001bb370)
        /home/kevlar/git-town/src/git/backend_commands.go:96 +0x90
github.com/git-town/git-town/v10/src/cmd.determineRepoConfig(0xc0001bb360)
        /home/kevlar/git-town/src/cmd/repo.go:69 +0x3b
github.com/git-town/git-town/v10/src/cmd.executeRepo(0x0)
        /home/kevlar/git-town/src/cmd/repo.go:59 +0x65
github.com/git-town/git-town/v10/src/cmd.repoCommand.func1(0xc0001cad00?, {0x10b8440?, 0x4?, 0xb8a470?})
        /home/kevlar/git-town/src/cmd/repo.go:40 +0x1c
github.com/spf13/cobra.(*Command).execute(0xc0001c0f00, {0x10b8440, 0x0, 0x0})
        /home/kevlar/git-town/vendor/github.com/spf13/cobra/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004300)
        /home/kevlar/git-town/vendor/github.com/spf13/cobra/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/kevlar/git-town/vendor/github.com/spf13/cobra/command.go:992
github.com/git-town/git-town/v10/src/cmd.Execute()
        /home/kevlar/git-town/src/cmd/core.go:33 +0x505
main.main()
        /home/kevlar/git-town/main.go:22 +0x25
```

Note that this returns nothing:

```
grep -r 'ci skip' .git 
```

I am 99% sure i did not use `ci skip` as a commit message in this repository. But I used that in commit messages (first line and below) recently on _other repositories_.

**Comment by ruudk** [comment]
Yeah I think mine were also commits somewhere in a branch

**Comment by joshRpowell** [comment]
long time user. thanks for the new release! 
similar issue after v10 upgrade
```
❯ git sync
panic: "wip" is not a valid remote branch name

goroutine 1 [running]:
github.com/git-town/git-town/v10/src/domain.NewRemoteBranchName({0x14000249272, 0x3})
	github.com/git-town/git-town/v10/src/domain/remote_branch_name.go:17 +0x8c
github.com/git-town/git-town/v10/src/git.determineSyncStatus({0x14000249229, 0x16}, {0x14000249271, 0x18})
	github.com/git-town/git-town/v10/src/git/backend_commands.go:194 +0xf8
github.com/git-town/git-town/v10/src/git.ParseVerboseBranchesOutput({0x14000248000, 0x21ee})
	github.com/git-town/git-town/v10/src/git/backend_commands.go:161 +0x4e0
github.com/git-town/git-town/v10/src/git.(*BackendCommands).BranchesSnapshot(0x140001b1370)
	github.com/git-town/git-town/v10/src/git/backend_commands.go:96 +0x9c
github.com/git-town/git-town/v10/src/execute.LoadBranches({0x140001b1360, 0x1, 0x0, 0x1, 0x140001b31d0, 0x1, 0x1, 0x0})
	github.com/git-town/git-town/v10/src/execute/load_branches.go:18 +0xa8
github.com/git-town/git-town/v10/src/cmd.determineSyncConfig(0x0, 0x140001b1360, 0x0)
	github.com/git-town/git-town/v10/src/cmd/sync.go:136 +0x114
github.com/git-town/git-town/v10/src/cmd.executeSync(0x0?, 0x0?, 0x0)
	github.com/git-town/git-town/v10/src/cmd/sync.go:70 +0x78
github.com/git-town/git-town/v10/src/cmd.syncCmd.func1(0x140001c2500?, {0x101630e20?, 0x4?, 0x100ef7ab7?})
	github.com/git-town/git-town/v10/src/cmd/sync.go:49 +0x74
github.com/spf13/cobra.(*Command).execute(0x140001ca300, {0x101630e20, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x140001a8000)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/git-town/git-town/v10/src/cmd.Execute()
	github.com/git-town/git-town/v10/src/cmd/core.go:33 +0x308
main.main()
	github.com/git-town/git-town/v10/main.go:22 +0x30
```
the following returns nothing
```
grep -r 'wip' .git
```

**Comment by joshuadavis** [comment]
Same issue here, this is making git town unuseable for me at the moment.  :(

```
% git town config setup
panic: "CS-666" is not a valid remote branch name

goroutine 1 [running]:
github.com/git-town/git-town/v10/src/domain.NewRemoteBranchName({0x140001dc235, 0x6})
	github.com/git-town/git-town/v10/src/domain/remote_branch_name.go:17 +0x8c
github.com/git-town/git-town/v10/src/git.determineSyncStatus({0x140001dc1dd, 0x17}, {0x140001dc234, 0x29})
	github.com/git-town/git-town/v10/src/git/backend_commands.go:194 +0xf8
github.com/git-town/git-town/v10/src/git.ParseVerboseBranchesOutput({0x140001dc000, 0x6b70})
	github.com/git-town/git-town/v10/src/git/backend_commands.go:161 +0x4e0
github.com/git-town/git-town/v10/src/git.(*BackendCommands).BranchesSnapshot(0x14000248010)
	github.com/git-town/git-town/v10/src/git/backend_commands.go:96 +0x9c
github.com/git-town/git-town/v10/src/execute.LoadBranches({0x14000248000, 0x0, 0x0, 0x0, 0x1400020a240, 0x1, 0x0, 0x0})
	github.com/git-town/git-town/v10/src/execute/load_branches.go:65 +0xb68
github.com/git-town/git-town/v10/src/cmd.executeConfigSetup(0x0)
	github.com/git-town/git-town/v10/src/cmd/config_setup.go:45 +0x108
github.com/git-town/git-town/v10/src/cmd.setupConfigCommand.func1(0x140001c2f00?, {0x10192ce20?, 0x4?, 0x1011f3ab7?})
	github.com/git-town/git-town/v10/src/cmd/config_setup.go:21 +0x28
github.com/spf13/cobra.(*Command).execute(0x140001aef00, {0x10192ce20, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x140001a6000)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/git-town/git-town/v10/src/cmd.Execute()
	github.com/git-town/git-town/v10/src/cmd/core.go:33 +0x308
main.main()
	github.com/git-town/git-town/v10/main.go:22 +0x30
```

**Comment by kevgo** [comment]
Apologies for the issues, this happens in an area that was rewritten for v10 and there are some bugs as this now code rolls out to more users. Can you please post the output of `git branch -vva`?

**Comment by kevgo** [comment]
This is caused by commits that contain special characters like `[` in their message.

**Comment by joshuadavis** [comment]
I'm not comfortable posting all that branch information here, but I can confirm that the commit messages contain square brackets.

**Comment by kevgo** [comment]
No problem, thanks for confirming my suspicion :slightly_smiling_face:

**Comment by kevgo** [comment]
Workaround until the bugfix (that I'm working on with high priority) gets released: avoid commit messages with `[` in them. I know that's not always possible.

**Comment by kevgo** [comment]
[v10.0.1](https://github.com/git-town/git-town/releases/tag/v10.0.1) fixes the issue if commits contain `[`. Please report if you run into additional problems. Thanks!

**Comment by ruudk** [comment]
Thanks for the quick fix 💙  It works perfectly!

**Comment by joshuadavis** [comment]
Yep.  Seems to work, thanks!

**Comment by jiexi** [comment]
Thank you, Kevin ❤️

**Comment by lud-wj** [comment]
Swiftly fixed :°)

Thank you !
