### ISSUE TITLE
git town sync fails, if a child branch is checked out on a different worktree

### ISSUE THREAD

**Issue by breml** [git-town/git-town#3297]
### Steps to reproduce

1. Have a feature branch and a child branch for the feature branch.
2. Have the child branch checked out in the git main worktree
3. work on the feature branch in a git worktree and start a `git town sync`

(I assume, that the same thing happens, if the checked out branches are the other way round (child branch on git worktree, feature branch on main worktree.)

### Command output

```shell
In my case, I first had to resolve a conflict during the initial sync, therefore the command the lead to the problem in this case was not `git town sync` but `git town continue`:


$ git town continue

[feature-branch] git rebase --continue
Recorded resolution for '<redacted>'.
[detached HEAD 450d32fb8] commit message
 Author: <redacted>
 14 files changed, 2707 insertions(+), 1467 deletions(-)
 create mode 100644 <redacted>
 create mode 100644 <redacted>
 create mode 100644 <redacted>
 create mode 100644 <redacted>
Successfully rebased and updated refs/heads/feature-branch.

[feature-branch] git push --force-with-lease --force-if-includes
Enter passphrase for key '.../id_ed25519_sk': 
Enumerating objects: 171, done.
Counting objects: 100% (171/171), done.
Delta compression using up to 12 threads
Compressing objects: 100% (137/137), done.
Writing objects: 100% (141/141), 43.29 KiB | 3.93 MiB/s, done.
Total 141 (delta 120), reused 5 (delta 3), pack-reused 0
remote: Resolving deltas: 100% (120/120), completed with 28 local objects.
To github.com:org/repo.git
 + 5ed567df2...12548fcf4 feature-branch -> feature-branch (forced update)


Error: cannot check out branch "feature-child-branch": 
----------------------------------------
Diagnostic information of failed command

COMMAND: git checkout feature-child-branch
ERROR: exit status 128
OUTPUT START
fatal: 'feature-child-branch' is already checked out at '/some/dir'

OUTPUT END
----------------------------------------

To continue after having resolved conflicts, run "git town continue".
To go back to where you started, run "git town undo".
To continue by skipping the current branch, run "git town skip".
```
```


### Additional information

_No response_

**Comment by kevgo** [comment]
There is an end-to-end test that proves the "parent of current branch is checked out in another worktree" scenario works: https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/merge_sync_strategy/worktree/parent_in_other_worktree.feature. In that case `git sync` simply skips syncing the parent.

Next step here is adding an end-to-end test for the scenario above:
- branch `parent` is in a linked worktree
- branch `child` is in the main worktree
- run `git sync` in the linked worktree

**Comment by kevgo** [comment]
@breml The way I understand your scenario, you sync the parent branch (you call it "feature branch") that is checked out in a linked worktree. In that case, `git sync` would not touch the child branch. Can you please clarify your scenario?

In the meantime, I have added an end-to-end test that verifies that `git sync` can be called from a linked worktree: features/sync/current_branch/feature_branch/merge_sync_strategy/worktree/sync_from_linked_worktree.feature.

**Comment by breml** [comment]
Right now I don't have such a case at hand, maybe I can re-test this next week.

**Comment by breml** [comment]
I have the same situation again (I on purpose checked out the branches as described in this scenario:

* branch `parent-branch` is in a linked worktree
* branch `child-branch` is in the main worktree
* run git sync in the linked worktree

This ends again with the same error that I already shared in the initial bug report:

```none
$ git town sync

[parent-branch] git fetch --prune --tags
Enter passphrase for key '.../id_ed25519_sk':
From github.com:company/repo
<redacted>
remote: Enumerating objects: 127, done.
remote: Counting objects: 100% (127/127), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 127 (delta 82), reused 106 (delta 80), pack-reused 0
Receiving objects: 100% (127/127), 33.20 KiB | 4.15 MiB/s, done.
Resolving deltas: 100% (82/82), completed with 30 local objects.
<redacted>

[parent-branch] git checkout master
Switched to branch 'master'
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

[master] git rebase origin/master
Successfully rebased and updated refs/heads/master.

[master] git checkout parent-branch
Switched to branch 'parent-branch'
Your branch is up to date with 'origin/parent-branch'.

[parent-branch] git rebase master
<redacted>

Error: exit status 1

To continue after having resolved conflicts, run "git town continue".
To go back to where you started, run "git town undo".
To continue by skipping the current branch, run "git town skip".

$ git add .

$ git town continue

[parent-branch] git rebase --continue
<redacted>
Successfully rebased and updated refs/heads/parent-branch.

[parent-branch] git push --force-with-lease --force-if-includes
Enter passphrase for key '.../id_ed25519_sk':
Enumerating objects: 114, done.
Counting objects: 100% (114/114), done.
Delta compression using up to 12 threads
Compressing objects: 100% (63/63), done.
Writing objects: 100% (70/70), 23.26 KiB | 7.75 MiB/s, done.
Total 70 (delta 58), reused 14 (delta 7), pack-reused 0
To github.com:company/repo.git
 + d55157e9d...282192f9a parent-branch -> parent-branch (forced update)


Error: cannot check out branch "child-branch": 
----------------------------------------
Diagnostic information of failed command

COMMAND: git checkout child-branch
ERROR: exit status 128
OUTPUT START
fatal: 'child-branch' is already checked out at '/some/directory'

OUTPUT END
----------------------------------------

To continue after having resolved conflicts, run "git town continue".
To go back to where you started, run "git town undo".
To continue by skipping the current branch, run "git town skip".
```

**Comment by breml** [comment]
Then I tried to continue with `git town skip`, which cause git town to crash with a panic:

```none
$ git town skip

[parent-branch] git reset --hard d55157e9d
HEAD is now at d55157e9d <redacted>

[parent-branch] git push --force-with-lease --force-if-includes
Enter passphrase for key '.../id_ed25519_sk':
Enumerating objects: 138, done.
Counting objects: 100% (138/138), done.
Delta compression using up to 12 threads
Compressing objects: 100% (83/83), done.
Writing objects: 100% (91/91), 25.01 KiB | 6.25 MiB/s, done.
Total 91 (delta 74), reused 16 (delta 7), pack-reused 0
To github.com:company/repo.git
 + 282192f9a...d55157e9d parent-branch -> parent-branch (forced update)
panic: runtime error: makeslice: cap out of range

goroutine 1 [running]:
github.com/git-town/git-town/v14/src/skip.removeOpcodesForCurrentBranch({0x0, 0x0, 0xc0002d05bb?})
        D:/a/git-town/git-town/src/skip/execute.go:49 +0x45
github.com/git-town/git-town/v14/src/skip.Execute({{0xdada08, 0xc000040120}, {0xc0002d05bb, 0x23}, 0x0, {0xc0000a4780, 0x5e}, 0xc000f28000, 0xc0000dd440, {0x1327c20, ...}, ...})
        D:/a/git-town/git-town/src/skip/execute.go:20 +0x11e
github.com/git-town/git-town/v14/src/cmd.executeSkip(0x0)
        D:/a/git-town/git-town/src/cmd/skip.go:89 +0x418
github.com/git-town/git-town/v14/src/cmd.skipCmd.func1(0xc00019e900?, {0x1327c20?, 0x4?, 0xca8ed5?})
        D:/a/git-town/git-town/src/cmd/skip.go:31 +0x1c
github.com/spf13/cobra.(*Command).execute(0xc000193808, {0x1327c20, 0x0, 0x0})
        D:/a/git-town/git-town/vendor/github.com/spf13/cobra/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc000168308)
        D:/a/git-town/git-town/vendor/github.com/spf13/cobra/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        D:/a/git-town/git-town/vendor/github.com/spf13/cobra/command.go:1039
github.com/git-town/git-town/v14/src/cmd.Execute()
        D:/a/git-town/git-town/src/cmd/core.go:38 +0x619
main.main()
        D:/a/git-town/git-town/main.go:18 +0x1e
```

**Comment by breml** [comment]
To problem seems still to be related to running `git town sync` on a linked worktree. I have now checked out `master` on the main worktree and then ran `git town sync` on the same `parent-branck` from above (which depends on master) and I get the same error but this time mentioning the `master` branch:

```none
Error: cannot check out branch "master": 
----------------------------------------
Diagnostic information of failed command

COMMAND: git checkout master
ERROR: exit status 128
OUTPUT START
fatal: 'master' is already checked out at '/some/directory'

OUTPUT END
----------------------------------------

To continue after having resolved conflicts, run "git town continue".
To go back to where you started, run "git town undo".
To continue by skipping the current branch, run "git town skip".
```

**Comment by breml** [comment]
Or the problem affects the complete stack of stacked branches `master -> feature-branch -> child-branch`. When ever I try `git town sync` on the `feature-branch`, which is checked out in a linked workspace and one of the other branches, that are part of the stack (e.g. `master` or `child-branch`) are checked out on the main worktree, git town fails.

**Comment by kevgo** [comment]
Thanks for the details again! We are making good progress here. It seems this time the actual sync goes through correctly (meaning all branches that are syncable in your situation get synced), and it fails when wrapping up.

I think the new failure happens when Git Town tries to restore the previously checked out Git branch. That's the branch you get to when running `git checkout -`. I assume the previous branch in your situation was `child-branch`.

**Comment by kevgo** [comment]
I could reproduce the issue when the previous branch is checked out in different worktree in #3532 and have committed a fix.

**Comment by kevgo** [comment]
Closing as fixed.
