### ISSUE TITLE
`git-town hack` panic if HEAD if detached

### ISSUE THREAD

**Issue by FirelightFlagboy** [git-town/git-town#3694]
### Steps to reproduce

1. On a git repository, checkout to an older commit in detached mode:

   ```shell
   git switch --detach $old_commit_sha
   ```

2. Create a new branch using `git-town hack`:

   ```shell
   git town hack foo
   ```

### Command output

```shell
[aca118d] git fetch --prune --tags
From github.com:[redacted]
 - [deleted]         (none)     -> origin/[redacted]
panic: "detached" is not a valid Git SHA

goroutine 1 [running]:
github.com/git-town/git-town/v14/src/git/gitdomain.NewSHA({0xc000380008?, 0x8?})
        github.com/git-town/git-town/v14/src/git/gitdomain/sha.go:15 +0x88
github.com/git-town/git-town/v14/src/git.ParseVerboseBranchesOutput({0xc000380000, 0xacf})
        github.com/git-town/git-town/v14/src/git/commands.go:763 +0x385
github.com/git-town/git-town/v14/src/git.(*Commands).BranchesSnapshot(0xc0002997e8, {0xdfadf0, 0xc000120c90})
        github.com/git-town/git-town/v14/src/git/commands.go:75 +0x9b
github.com/git-town/git-town/v14/src/execute.LoadRepoSnapshot({{0xdfd520, 0xc000120c90}, {0xc00011b090}, {0xc000206ed0, 0xc000206ff0}, {0xc000120ca8}, 0x1, {0xc000120ba0}, {0xdf9660, 0xc0002071d0}, ...})
        github.com/git-town/git-town/v14/src/execute/load_repo_snapshot.go:67 +0x33d
github.com/git-town/git-town/v14/src/cmd.determineHackData({_, _, _}, {{0xdfd520, 0xc000120c90}, {0xc00011b090}, {0xc000206ed0, 0xc000206ff0}, {0xc000120ba0}, {0xdf9660, ...}, ...}, ...)
        github.com/git-town/git-town/v14/src/cmd/hack.go:168 +0x33a
github.com/git-town/git-town/v14/src/cmd.executeHack({0xc00011ca90, 0x1, 0x1}, 0x0, 0x0)
        github.com/git-town/git-town/v14/src/cmd/hack.go:68 +0x16a
github.com/git-town/git-town/v14/src/cmd.hackCmd.func1(0xc00020cc08, {0xc00011ca90, 0x1, 0x1})
        github.com/git-town/git-town/v14/src/cmd/hack.go:48 +0x65
github.com/spf13/cobra.(*Command).execute(0xc00020cc08, {0xc00011ca60, 0x1, 0x1})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001ea308)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/git-town/git-town/v14/src/cmd.Execute()
        github.com/git-town/git-town/v14/src/cmd/core.go:38 +0x619
main.main()
        github.com/git-town/git-town/v14/main.go:18 +0x1e
```

### Additional information

I would have expect that `git-town` would be able to create the new branch from the main branch (`master` in my case, that would be equivalent to `git switch --create foo origin/master`).

```
git-town: 14.2.2
```

**Comment by kevgo** [comment]
Nice edge case! Yes, Git Town should create the new feature branch from the main branch in this situation. Is there a reason why you want the new branch cut from `origin/master` and not `master` in your example?

**Comment by FirelightFlagboy** [comment]
The reason for `origin/master` over `master` is it will use the latest commit on `master` without having the checkout into `master` then doing a `git pull` (but still require `git fetch` to have the latest commit from the remote).

It's how I do `git` when I'm not using `git-town`.

But that not required for `git-town` since it do the `checkout master` automatically.

**Comment by kevgo** [comment]
Cool idea.
