### ISSUE TITLE
panic when running git town commands from detached head state

### ISSUE THREAD

**Issue by mball-agathos** [git-town/git-town#3847]
### Steps to reproduce

1. Go into Git's "detached HEAD" state (e.g., by directly checking out a particular hash)
2. Run a command like `git town switch` or `git town sync`

### Command output

```shell
$ git town switch
panic: "detached" is not a valid Git SHA

goroutine 1 [running]:
github.com/git-town/git-town/v15/internal/git/gitdomain.NewSHA({0xc000308008?, 0x8?})
	D:/a/git-town/git-town/internal/git/gitdomain/sha.go:15 +0x88
github.com/git-town/git-town/v15/internal/git.ParseVerboseBranchesOutput({0xc000308000, 0x1786})
	D:/a/git-town/git-town/internal/git/commands.go:764 +0x385
github.com/git-town/git-town/v15/internal/git.(*Commands).BranchesSnapshot(0xc0000e9f68, {0xe18130, 0xc0000100d8})
	D:/a/git-town/git-town/internal/git/commands.go:74 +0x9b
github.com/git-town/git-town/v15/internal/execute.LoadRepoSnapshot({{0xe19350, 0xc0000100d8}, {0xc000120fb8}, {0xc0001e5500, 0xc00009e0f0}, {0xc0000100f0}, 0x0, {0xc0000100a8}, {0xe169e0, 0xc00009e3f0}, ...})
	D:/a/git-town/git-town/internal/execute/load_repo_snapshot.go:68 +0x33d
github.com/git-town/git-town/v15/internal/cmd.determineSwitchData({{0xe19350, 0xc0000100d8}, {0xc000120fb8}, {0xc0001e5500, 0xc00009e0f0}, {0xc0000100a8}, {0xe169e0, 0xc00009e3f0}, {0xc0001e5350, 0xc000122a30}, ...}, ...)
	D:/a/git-town/git-town/internal/cmd/switch.go:92 +0x25c
github.com/git-town/git-town/v15/internal/cmd.executeSwitch(0x0, 0x0)
	D:/a/git-town/git-town/internal/cmd/switch.go:53 +0x149
github.com/git-town/git-town/v15/internal/cmd.switchCmd.func1(0xc000202608, {0x13f7f00?, 0x4?, 0xd02359?})
	D:/a/git-town/git-town/internal/cmd/switch.go:33 +0x45
github.com/spf13/cobra.(*Command).execute(0xc000202608, {0x13f7f00, 0x0, 0x0})
	D:/a/git-town/git-town/vendor/github.com/spf13/cobra/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d6308)
	D:/a/git-town/git-town/vendor/github.com/spf13/cobra/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	D:/a/git-town/git-town/vendor/github.com/spf13/cobra/command.go:1039
github.com/git-town/git-town/v15/internal/cmd.Execute()
	D:/a/git-town/git-town/internal/cmd/core.go:39 +0x652
main.main()
	D:/a/git-town/git-town/main.go:18 +0x1e
```

### Additional information

panicking seems okay when running `git town sync` (since you don't have the correct context to run sync from), but is not helpful when running something like `git town switch` in which you're trying to change branches and don't really care what branch you're currently on.

**Comment by kevgo** [comment]
Thank you for bringing this to our attention! It looks like this bug is related to https://github.com/git-town/git-town/issues/3694. It seems to be affecting more commands than just `hack`, and potentially impacting a broader range of users as well.
