### ISSUE TITLE
switch: panic when there are no matching branches

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#3979]
### Steps to reproduce

- have only feature branches
- run `git town switch --type=contribution`

buggy behavior
- the list of branches is empty
- when hitting ENTER it crashes

### Command output

```shell
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/git-town/git-town/v16/internal/cli/dialog/components/list.List[...].SelectedEntry(...)
        /Users/kevlar/d/git-town/internal/cli/dialog/components/list/list.go:180
github.com/git-town/git-town/v16/internal/cli/dialog/components/list.List[...].SelectedData(...)
        /Users/kevlar/d/git-town/internal/cli/dialog/components/list/list.go:176
github.com/git-town/git-town/v16/internal/cli/dialog.SwitchBranch({0x1400026ad50, 0x0, 0x8?}, 0x0, 0x1, {0x103d9f340, 0x0, 0x0})
        /Users/kevlar/d/git-town/internal/cli/dialog/switch_branch.go:38 +0x374
github.com/git-town/git-town/v16/internal/cmd.executeSwitch({0x14000112570, 0x0, 0x1}, 0x0, 0x0, 0x0, {0x140001164e8, 0x1, 0x1})
        /Users/kevlar/d/git-town/internal/cmd/switch.go:72 +0x3fc
github.com/git-town/git-town/v16/internal/cmd.switchCmd.func1(0x14000228f08, {0x14000112570, 0x0, 0x1})
        /Users/kevlar/d/git-town/internal/cmd/switch.go:42 +0xd4
github.com/spf13/cobra.(*Command).execute(0x14000228f08, {0x14000112550, 0x1, 0x1})
        /Users/kevlar/d/git-town/vendor/github.com/spf13/cobra/command.go:985 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x1400016a308)
        /Users/kevlar/d/git-town/vendor/github.com/spf13/cobra/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/kevlar/d/git-town/vendor/github.com/spf13/cobra/command.go:1041
github.com/git-town/git-town/v16/internal/cmd.Execute()
        /Users/kevlar/d/git-town/internal/cmd/core.go:40 +0x3c8
main.main()
        /Users/kevlar/d/git-town/main.go:18 +0x28
```

### Additional information

It should exit with a message saying that there are no branches to switch to.

**Comment by kevgo** [comment]
This is now available as part of [Git Town 16.2](https://github.com/git-town/git-town/releases/tag/v16.2.0). Enjoy!
