### ISSUE TITLE
Hitting NotFoundGraphError2: Graph.addDirectedEdge: source node error in CI

### ISSUE THREAD

**Issue by EngHabu** [git-town/git-town#4195]
We use git-town actions to populate the stack view in the PR description.
It has been working well until recently (today?) where we started hitting this:

```
/home/runner/work/_actions/git-town/action/v1/dist/index.js:24877
        throw new NotFoundGraphError("Graph.".concat(name, ': source node "').concat(source, '" not found.'));
              ^

NotFoundGraphError2: Graph.addDirectedEdge: source node "<a branch name here>" not found.
    at addEdge (/home/runner/work/_actions/git-town/action/v1/dist/index.js:24877:15)
    at Graph.<computed> [as addDirectedEdge] (/home/runner/work/_actions/git-town/action/v1/dist/index.js:26139:20)
    at /home/runner/work/_actions/git-town/action/v1/dist/index.js:42861:15
    at Array.forEach (<anonymous>)
    at main (/home/runner/work/_actions/git-town/action/v1/dist/index.js:42860:[16](https://github.com/unionai/cloud/actions/runs/11693203423/job/32564253997?pr=9227#step:3:22))
    at run (/home/runner/work/_actions/git-town/action/v1/dist/index.js:47005:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.13.1
```

It's unclear to me what's going on... The referenced branch is not related to my PR and isn't part of the stack...

**Comment by kevgo** [comment]
Sorry about the delayed response, it's been a crazy week :exploding_head: This is a problem with https://github.com/git-town/action. @tranhl can you please take a look? :pray:

**Comment by tranhl** [comment]
@kevgo No problems I'll take it from here 😄. @EngHabu Thanks for taking the time to report this! I've created an issue [in the action's repository](https://github.com/git-town/action/issues/42) to track this issue. Lets move the discussion to there.
